export const CITY_TO_CSV = {
  "Alta": "rosepark.csv",
  "Bluffdale": "utahtechcenter.csv",
  "Copperton": "copperview.csv",
  "Cottonwood Heights": "hawthorne.csv",
  "Draper": "constellationlabs.csv",
  "Emigration Canyon": "bv.csv",
  "Granite": "hawthorne.csv",
  "Herriman": "copperview.csv",
  "Holladay": "hawthorne.csv",
  "Kearns": "copperview.csv",
  "Magna": "lakepark.csv",
  "Midvale": "hawthorne.csv",
  "Millcreek": "bv.csv",
  "Murray": "hawthorne.csv",
  "Riverton": "utahtechcenter.csv",
  "Salt Lake City": "rosepark.csv",
  "Sandy City": "constellationlabs.csv",
  "South Jordan": "utahtechcenter.csv",
  "South Salt Lake": "hawthorne.csv",
  "Taylorsville": "copperview.csv",
  "West Jordan": "cavecamp.csv",
  "West Valley City": "lakepark.csv",
  "White City": "constellationlabs.csv"
};